[workspace]
authors = ["kaspermunch <kaspermunch@birc.au.dk>"]
channels = ["conda-forge", "bioconda", "munch-group"]
name = "psmc-exercise"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyter = ">=1.1.1,<2"
seaborn = ">=0.13.2,<0.14"
git = ">=2.53.0,<3"
gh = ">=2.87.0,<3"
ipykernel = ">=7.2.0,<8"
nbconvert = ">=7.17.0,<8"
vscodenb = ">=0.1.34,<0.2"
samtools = ">=1.23,<2"
bcftools = ">=1.23,<2"
psmc = ">=0.6.5,<0.7"
